spring:
  application:
    name: t-study
  data:
    mongodb:
      uri: mongodb://root:1204@localhost:27017/t-study

server:
  port: 1204

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    io.github.touchsun: DEBUG
  file:
    name: logs/application.log