
### get all system check
GET {{host}}{{version}}/system/role
Accept: application/json

### add one system role
POST {{host}}{{version}}/system/role
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsZWUubGkiLCJpYXQiOjE3MjIwOTU3NzUsImV4cCI6MTcyMjEzMTc3NX0.XFk6papLV7vW5umQ_K1-6XnI_dQ0Mx87cpLAGrIQmoU

{
  "name": "管理员角色333",
  "code": "admin"
}

### update one system role
PUT {{host}}{{version}}/system/role
Accept: application/json
Content-Type: application/json

{
  "id": "66a347989b62464548af9b95",
  "name": "管理员角色002",
  "code": "admin"
}

### delete one system role
DELETE {{host}}{{version}}/system/role/66a3331d4a5878326e3f7455
Accept: application/json
