
### get all system check
GET {{host}}{{version}}/system/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b3VjaHN1bjAxIiwiaWF0IjoxNzIyMTQ0MzY0LCJleHAiOjE3MjIxODAzNjR9.9Y7MVpRgtTnay0OYhVmUNaI4pqvgwsAG8dLQNl7uo8U

### add one system user
POST {{host}}{{version}}/system/user
Accept: application/json
Content-Type: application/json

{
  "username": "touchsun",
  "password": "123456",
  "status": "1"
}

### login
POST {{host}}{{version}}/system/user/login
Accept: application/json, text/plain, */*
Content-Type: application/json

{
  "username": "touchsun01",
  "password": "123456"
}

### register
POST {{host}}{{version}}/system/user/register
Accept: application/json
Content-Type: application/json

{
  "username": "touchsun01",
  "password": "123456"
}

### update one system user
PUT {{host}}{{version}}/system/user/66a3433df05e734d3d325ec1
Accept: application/json
Content-Type: application/json

{
  "username": "touchsun01",
  "password": "123456",
  "status": "1"
}

### delete one system user
DELETE {{host}}{{version}}/system/user/66a3331d4a5878326e3f7455
Accept: application/json
